name: Linting

on:
    - push

jobs:
    run:
        name: Run Linting
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.9"]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install deps
              run: |
                python -m pip install -r requirements.txt
                python -m pip install -r requirements-dev.txt

            - name: Lint
              run: flake8 --config flake8.conf
